#!/usr/bin/env python

import glob

print("generating README.md..")

readMeContent = ""
with open("intro", 'r') as f:
    readMeContent = f.read().strip() + "\n"

paths = glob.glob("img/*")
for path in paths:
    readMeContent += "![](" + path + ")\n"
with open("README.md", 'w+') as f:
    f.write(readMeContent.strip())

print("done.")
